# Generated by Django 4.2.17 on 2025-01-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('u', 'unit'), ('oz', 'ounces')], default='u', max_length=2),
        ),
    ]
